# Generated by Django 5.2.7 on 2026-10-06 08:00

import baibu.users.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='Country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', baibu.users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('in_app', 'In app'), ('web', 'Web')], max_length=32)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='submitted', max_length=32)),
                ('requester_name', models.CharField(blank=True, max_length=255)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('request_details', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account deletion request',
                'verbose_name_plural': 'Account deletion requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='users_accou_status_1dabb9_idx'), models.Index(fields=['source', 'requested_at'], name='users_accou_source_56c838_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'approved', 'in_progress', 'failed'])), fields=('user',), name='users_one_open_account_deletion_request_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('none', 'No data use'), ('eval_only', 'Evaluation only'), ('training_eligible', 'Training eligible')], max_length=32)),
                ('source', models.CharField(help_text='Where the decision was made, e.g. account_settings.', max_length=64)),
                ('scope', models.CharField(help_text='What the decision covers, e.g. platform or chat.', max_length=64)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent record',
                'verbose_name_plural': 'Consent records',
                'ordering': ['-granted_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'scope', '-granted_at'], name='users_conse_user_id_03bf57_idx')],
            },
        ),
    ]
