# Generated by Django 5.2.7 on 2026-10-06 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Enter a phone number in international format, starting with + and the country code.', regex='^\\+[1-9]\\d{6,14}$')], verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone number verified'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_verified', True)), fields=('phone',), name='users_unique_verified_phone'),
        ),
    ]
