# Generated by Django 5.2.7 on 2026-10-06 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=64)),
                ('dimension', models.CharField(blank=True, default='', max_length=128)),
                ('value', models.BigIntegerField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily metric',
                'verbose_name_plural': 'Daily metrics',
                'ordering': ['date', 'name', 'dimension'],
                'indexes': [models.Index(fields=['name', 'date'], name='metrics_dai_name_4dc068_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'name', 'dimension'), name='metrics_one_value_per_day')],
            },
        ),
    ]
