# Generated by Django 5.2.7 on 2026-10-06 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('pot_key', models.CharField(max_length=512)),
                ('content_hash', models.CharField(max_length=64)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source strings',
                'verbose_name_plural': 'Source strings',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='TranslationCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=24, unique=True, verbose_name='Language')),
                ('draft_key', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='localization.translationsource')),
            ],
            options={
                'verbose_name': 'Translation catalogue',
                'verbose_name_plural': 'Translation catalogues',
                'ordering': ['language_code'],
                'permissions': [('edit_translations', 'Can edit and publish interface translations')],
            },
        ),
        migrations.CreateModel(
            name='TranslationPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=24, verbose_name='Language')),
                ('version', models.PositiveIntegerField()),
                ('po_key', models.CharField(max_length=512)),
                ('mo_key', models.CharField(max_length=512)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('translated_count', models.PositiveIntegerField(default=0)),
                ('fuzzy_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_from', models.ForeignKey(blank=True, help_text='Set for a restore.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='localization.translationpublication')),
            ],
            options={
                'verbose_name': 'Translation publication',
                'verbose_name_plural': 'Translation publications',
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('language_code', 'version'), name='localization_unique_version')],
            },
        ),
    ]
