# Generated by Django 5.2.7 on 2026-10-06 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=24, verbose_name='Language')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('needs_review', 'Needs review'), ('rejected', 'Rejected'), ('issue', 'Issue')], db_index=True, default='pending', max_length=16)),
                ('consent_tier', models.CharField(choices=[('none', 'No data use'), ('eval_only', 'Evaluation only'), ('training_eligible', 'Training eligible')], max_length=32)),
                ('raw_key', models.CharField(max_length=512)),
                ('clean_key', models.CharField(blank=True, max_length=512)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('excerpt', models.TextField(blank=True)),
                ('cleaner', models.CharField(blank=True, help_text='Cleaner (and model) that produced it.', max_length=128)),
                ('redaction_count', models.PositiveIntegerField(blank=True, null=True)),
                ('toxicity_detected', models.BooleanField(blank=True, null=True)),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, help_text='0 to 100.', null=True)),
                ('detected_language', models.CharField(blank=True, max_length=24)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('decision_reason', models.CharField(blank=True, max_length=512)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.consentrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
