# Generated by Django 5.2.7 on 2026-10-06 12:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('language_code', models.CharField(blank=True, max_length=24)),
                ('consent_tier', models.CharField(choices=[('none', 'No data use'), ('eval_only', 'Evaluation only'), ('training_eligible', 'Training eligible')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('model', models.CharField(help_text="LiteLLM model name, or 'mock'.", max_length=255)),
                ('api_base', models.CharField(blank=True, help_text='Endpoint URL, if the model needs one.', max_length=512)),
                ('api_key_env', models.CharField(blank=True, help_text='Name of the environment variable that holds the API key. Keys are never stored here.', max_length=128)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Extra parameters for every call, e.g. {"temperature": 0.7}.')),
                ('is_default', models.BooleanField(default=False, help_text='Used for new replies. Only one can be the default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model variant',
                'verbose_name_plural': 'Model variants',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='chat_one_default_model')],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='system', max_length=64)),
                ('version', models.PositiveIntegerField(editable=False)),
                ('body', models.TextField(help_text='A Django template. Available: platform, user_name, language_code, language_name.')),
                ('active', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt',
                'verbose_name_plural': 'Prompts',
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('prompt_version', models.CharField(blank=True, max_length=80)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='chat.conversation')),
                ('model_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.modelvariant')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.prompt')),
                ('triggering_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='chat.message')),
            ],
            options={
                'verbose_name': 'Run',
                'verbose_name_plural': 'Runs',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='chat.run'),
        ),
        migrations.CreateModel(
            name='ConversationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chat.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chat.message')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chat.run')),
            ],
            options={
                'verbose_name': 'Conversation event',
                'verbose_name_plural': 'Conversation events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='chat_prompt_name_version'),
        ),
        migrations.AddConstraint(
            model_name='prompt',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name',), name='chat_one_active_prompt_per_name'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'idempotency_key'), name='chat_message_idempotency'),
        ),
    ]
