# Generated by Django 5.2.7 on 2026-10-06 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('call_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('arguments', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='chat.run')),
            ],
            options={
                'verbose_name': 'Tool invocation',
                'verbose_name_plural': 'Tool invocations',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
