# Generated by Django 5.2.7 on 2026-10-06 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_tool_invocations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('harmful', 'Harmful or offensive'), ('incorrect', 'Wrong or misleading'), ('other', 'Something else')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Problem confirmed'), ('dismissed', 'No problem found')], db_index=True, default='open', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='chat.conversation')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='chat.message')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reported reply',
                'verbose_name_plural': 'Reported replies',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'reported_by'), name='chat_flag_once_per_message')],
            },
        ),
    ]
