# Generated by Django 5.2.7 on 2026-10-06 12:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveIntegerField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('provider', models.CharField(blank=True, max_length=128)),
                ('language', models.CharField(blank=True, max_length=24)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_clips', to='chat.conversation')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='chat.message')),
            ],
            options={
                'verbose_name': 'Audio clip',
                'verbose_name_plural': 'Audio clips',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
