# Generated by Django 5.2.7 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_audio_clips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, help_text='Helps the tagger decide; not shown to users.', max_length=500)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=24)),
                ('intent', models.CharField(blank=True, max_length=32)),
                ('tagger', models.CharField(blank=True, max_length=255)),
                ('tagged_activity_at', models.DateTimeField()),
                ('tagged_at', models.DateTimeField(auto_now=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='chat.conversation')),
                ('topics', models.ManyToManyField(blank=True, related_name='tags', to='chat.topic')),
            ],
            options={
                'verbose_name': 'Conversation tag',
                'verbose_name_plural': 'Conversation tags',
            },
        ),
    ]
